export enum PaymentStatus {
  CANCELED = 'CANCELED',
  PENDING = 'PENDING',
  UNPAID = 'UNPAID',
  PAID = 'PAID',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}
