export enum SubscriptionFeatureKey {
  STRIPE_PAYMENTS = 'STRIPE_PAYMENTS',
  STORE_CUSTOMIZATION = 'STORE_CUSTOMIZATION',
  COUPONS = 'COUPONS',
  STAFF_MANAGEMENT = 'STAFF_MANAGEMENT',
  PRODUCT_IMPORT_EXPORT = 'PRODUCT_IMPORT_EXPORT',
  CUSTOM_DOMAIN = 'CUSTOM_DOMAIN',
  ADVANCED_ANALYTICS = 'ADVANCED_ANALYTICS',
  ADVANCED_REPORTS = 'ADVANCED_REPORTS',
  SEO_TOOLS = 'SEO_TOOLS',
  AUDIT_LOGS = 'AUDIT_LOGS',
  PRIORITY_SUPPORT = 'PRIORITY_SUPPORT',
}
