export enum SubscriptionLimitKey {
  STORAGE_BYTES = 'STORAGE_BYTES',
  DATABASE_BYTES = 'DATABASE_BYTES',
  STORE_ADMINS = 'STORE_ADMINS',
  COUPONS_PER_MONTH = 'COUPONS_PER_MONTH',
  PRODUCTS = 'PRODUCTS',
}
